# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.hostname = "web-dev"
  
  config.vm.provision "shell", path: "provision.sh"
  config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx", auto_correct: true
  config.vm.synced_folder "www", "/vagrant/www"
  config.vm.synced_folder "sites-enabled", "/vagrant/sites-enabled"
end
